a_quant_type: None
aa: rand-m9-mstd0.5-inc1
ag_quant_type: None
amp: false
apex_amp: false
aug_repeats: 0
aug_splits: 0
batch_size: 32
bce_loss: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
channels_last: false
checkpoint_hist: 1
class_map: ''
clip_grad: null
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: null
cutmix: 1.0
cutmix_minmax: null
data_dir: /home/shkim/data/
dataset: torch/cifar100
dataset_download: false
decay_epochs: 100
decay_milestones:
- 30
- 60
decay_rate: 0.1
direct_resize: false
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: 0.0
epoch_repeats: 0.0
epochs: 100
eval_metric: top1
evaluate: true
experiment: ''
freeze_reg: false
fuser: ''
gp: null
grad_checkpointing: false
hflip: 0.5
img_size: 224
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd_loss: false
layer_decay: null
local_rank: 0
log_interval: 50
log_wandb: false
lr: 5.0e-05
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 1.0e-08
mixup: 0.8
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: fullbits_vit_base_patch16_224
model_ema: true
model_ema_decay: 0.99992
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_ddp_bb: false
no_prefetcher: false
no_resume_opt: false
num_classes: 100
opt: adamw
opt_betas: null
opt_eps: null
output: /home/shkim/SSF_org/SSF/prob/cifar100/probe_full_0reg
patience_epochs: 10
pin_mem: false
pretrained: true
prompt_search_mode: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
register_num: 8
remode: pixel
reprob: 0.25
resplit: false
resume: /home/shkim/SSF_org/SSF/output/fullbits_vit_base_patch16_224/cifar100/full_8reg_32_4e_4_for_last_checkpoint/fullbits_vit_base_patch16_224-full_8reg_32_4e_4_for_last_checkpoint/8reg_with_4e-4LR_32BS_110Epoch.tar
resume_mode: None
sample_data_path: null
sample_eval: false
save_best_cp: false
save_cp_point: null
save_custom_cp: false
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 42
simple_aug: false
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
torchscript: false
train_interpolation: random
train_split: train
tta: 0
tuning_mode: null
use_multi_epochs_loader: false
val_split: validation
validation_batch_size: null
vflip: 0.0
warmup_epochs: 10
warmup_lr: 1.0e-07
weight_decay: 0.05
worker_seeding: all
workers: 8
